[project]
name = "YodelKey"
version = "1.0.0"
description = "share links & more with a yodel"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "werkzeug>=3.1.4"
]

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = ["ANN201", "INP001"]